// Tweet.java

// Generated by https://quicktype.io

package io.quicktype;

import java.util.Map;

public class Tweet {
    private String createdAt;
    private long id;
    private String idStr;
    private String text;
    private boolean truncated;
    private TweetEntities entities;
    private String source;
    private Object inReplyToStatusID;
    private Object inReplyToStatusIDStr;
    private Object inReplyToUserID;
    private Object inReplyToUserIDStr;
    private Object inReplyToScreenName;
    private User user;
    private Object geo;
    private Object coordinates;
    private Object place;
    private Object contributors;
    private boolean isQuoteStatus;
    private long retweetCount;
    private long favoriteCount;
    private boolean favorited;
    private boolean retweeted;
    private boolean possiblySensitive;
    private boolean possiblySensitiveAppealable;
    private String lang;

    public String getCreatedAt() { return createdAt; }
    public void setCreatedAt(String value) { this.createdAt = value; }

    public long getID() { return id; }
    public void setID(long value) { this.id = value; }

    public String getIDStr() { return idStr; }
    public void setIDStr(String value) { this.idStr = value; }

    public String getText() { return text; }
    public void setText(String value) { this.text = value; }

    public boolean getTruncated() { return truncated; }
    public void setTruncated(boolean value) { this.truncated = value; }

    public TweetEntities getEntities() { return entities; }
    public void setEntities(TweetEntities value) { this.entities = value; }

    public String getSource() { return source; }
    public void setSource(String value) { this.source = value; }

    public Object getInReplyToStatusID() { return inReplyToStatusID; }
    public void setInReplyToStatusID(Object value) { this.inReplyToStatusID = value; }

    public Object getInReplyToStatusIDStr() { return inReplyToStatusIDStr; }
    public void setInReplyToStatusIDStr(Object value) { this.inReplyToStatusIDStr = value; }

    public Object getInReplyToUserID() { return inReplyToUserID; }
    public void setInReplyToUserID(Object value) { this.inReplyToUserID = value; }

    public Object getInReplyToUserIDStr() { return inReplyToUserIDStr; }
    public void setInReplyToUserIDStr(Object value) { this.inReplyToUserIDStr = value; }

    public Object getInReplyToScreenName() { return inReplyToScreenName; }
    public void setInReplyToScreenName(Object value) { this.inReplyToScreenName = value; }

    public User getUser() { return user; }
    public void setUser(User value) { this.user = value; }

    public Object getGeo() { return geo; }
    public void setGeo(Object value) { this.geo = value; }

    public Object getCoordinates() { return coordinates; }
    public void setCoordinates(Object value) { this.coordinates = value; }

    public Object getPlace() { return place; }
    public void setPlace(Object value) { this.place = value; }

    public Object getContributors() { return contributors; }
    public void setContributors(Object value) { this.contributors = value; }

    public boolean getIsQuoteStatus() { return isQuoteStatus; }
    public void setIsQuoteStatus(boolean value) { this.isQuoteStatus = value; }

    public long getRetweetCount() { return retweetCount; }
    public void setRetweetCount(long value) { this.retweetCount = value; }

    public long getFavoriteCount() { return favoriteCount; }
    public void setFavoriteCount(long value) { this.favoriteCount = value; }

    public boolean getFavorited() { return favorited; }
    public void setFavorited(boolean value) { this.favorited = value; }

    public boolean getRetweeted() { return retweeted; }
    public void setRetweeted(boolean value) { this.retweeted = value; }

    public boolean getPossiblySensitive() { return possiblySensitive; }
    public void setPossiblySensitive(boolean value) { this.possiblySensitive = value; }

    public boolean getPossiblySensitiveAppealable() { return possiblySensitiveAppealable; }
    public void setPossiblySensitiveAppealable(boolean value) { this.possiblySensitiveAppealable = value; }

    public String getLang() { return lang; }
    public void setLang(String value) { this.lang = value; }
}

// TweetEntities.java

package io.quicktype;

import java.util.Map;

public class TweetEntities {
    private Object[] hashtags;
    private Object[] symbols;
    private Object[] userMentions;
    private URL[] urls;

    public Object[] getHashtags() { return hashtags; }
    public void setHashtags(Object[] value) { this.hashtags = value; }

    public Object[] getSymbols() { return symbols; }
    public void setSymbols(Object[] value) { this.symbols = value; }

    public Object[] getUserMentions() { return userMentions; }
    public void setUserMentions(Object[] value) { this.userMentions = value; }

    public URL[] getUrls() { return urls; }
    public void setUrls(URL[] value) { this.urls = value; }
}

// URL.java

package io.quicktype;

import java.util.Map;

public class URL {
    private String url;
    private String expandedURL;
    private String displayURL;
    private long[] indices;

    public String getURL() { return url; }
    public void setURL(String value) { this.url = value; }

    public String getExpandedURL() { return expandedURL; }
    public void setExpandedURL(String value) { this.expandedURL = value; }

    public String getDisplayURL() { return displayURL; }
    public void setDisplayURL(String value) { this.displayURL = value; }

    public long[] getIndices() { return indices; }
    public void setIndices(long[] value) { this.indices = value; }
}

// User.java

package io.quicktype;

import java.util.Map;

public class User {
    private long id;
    private String idStr;
    private String name;
    private String screenName;
    private String location;
    private String description;
    private String url;
    private UserEntities entities;
    private boolean userProtected;
    private long followersCount;
    private long friendsCount;
    private long listedCount;
    private String createdAt;
    private long favouritesCount;
    private Object utcOffset;
    private Object timeZone;
    private Object geoEnabled;
    private boolean verified;
    private long statusesCount;
    private String lang;
    private Object contributorsEnabled;
    private Object isTranslator;
    private Object isTranslationEnabled;
    private String profileBackgroundColor;
    private String profileBackgroundImageURL;
    private String profileBackgroundImageURLHTTPS;
    private Object profileBackgroundTile;
    private String profileImageURL;
    private String profileImageURLHTTPS;
    private String profileBannerURL;
    private String profileLinkColor;
    private String profileSidebarBorderColor;
    private String profileSidebarFillColor;
    private String profileTextColor;
    private Object profileUseBackgroundImage;
    private Object hasExtendedProfile;
    private boolean defaultProfile;
    private boolean defaultProfileImage;
    private Object following;
    private Object followRequestSent;
    private Object notifications;
    private String translatorType;

    public long getID() { return id; }
    public void setID(long value) { this.id = value; }

    public String getIDStr() { return idStr; }
    public void setIDStr(String value) { this.idStr = value; }

    public String getName() { return name; }
    public void setName(String value) { this.name = value; }

    public String getScreenName() { return screenName; }
    public void setScreenName(String value) { this.screenName = value; }

    public String getLocation() { return location; }
    public void setLocation(String value) { this.location = value; }

    public String getDescription() { return description; }
    public void setDescription(String value) { this.description = value; }

    public String getURL() { return url; }
    public void setURL(String value) { this.url = value; }

    public UserEntities getEntities() { return entities; }
    public void setEntities(UserEntities value) { this.entities = value; }

    public boolean getUserProtected() { return userProtected; }
    public void setUserProtected(boolean value) { this.userProtected = value; }

    public long getFollowersCount() { return followersCount; }
    public void setFollowersCount(long value) { this.followersCount = value; }

    public long getFriendsCount() { return friendsCount; }
    public void setFriendsCount(long value) { this.friendsCount = value; }

    public long getListedCount() { return listedCount; }
    public void setListedCount(long value) { this.listedCount = value; }

    public String getCreatedAt() { return createdAt; }
    public void setCreatedAt(String value) { this.createdAt = value; }

    public long getFavouritesCount() { return favouritesCount; }
    public void setFavouritesCount(long value) { this.favouritesCount = value; }

    public Object getUTCOffset() { return utcOffset; }
    public void setUTCOffset(Object value) { this.utcOffset = value; }

    public Object getTimeZone() { return timeZone; }
    public void setTimeZone(Object value) { this.timeZone = value; }

    public Object getGeoEnabled() { return geoEnabled; }
    public void setGeoEnabled(Object value) { this.geoEnabled = value; }

    public boolean getVerified() { return verified; }
    public void setVerified(boolean value) { this.verified = value; }

    public long getStatusesCount() { return statusesCount; }
    public void setStatusesCount(long value) { this.statusesCount = value; }

    public String getLang() { return lang; }
    public void setLang(String value) { this.lang = value; }

    public Object getContributorsEnabled() { return contributorsEnabled; }
    public void setContributorsEnabled(Object value) { this.contributorsEnabled = value; }

    public Object getIsTranslator() { return isTranslator; }
    public void setIsTranslator(Object value) { this.isTranslator = value; }

    public Object getIsTranslationEnabled() { return isTranslationEnabled; }
    public void setIsTranslationEnabled(Object value) { this.isTranslationEnabled = value; }

    public String getProfileBackgroundColor() { return profileBackgroundColor; }
    public void setProfileBackgroundColor(String value) { this.profileBackgroundColor = value; }

    public String getProfileBackgroundImageURL() { return profileBackgroundImageURL; }
    public void setProfileBackgroundImageURL(String value) { this.profileBackgroundImageURL = value; }

    public String getProfileBackgroundImageURLHTTPS() { return profileBackgroundImageURLHTTPS; }
    public void setProfileBackgroundImageURLHTTPS(String value) { this.profileBackgroundImageURLHTTPS = value; }

    public Object getProfileBackgroundTile() { return profileBackgroundTile; }
    public void setProfileBackgroundTile(Object value) { this.profileBackgroundTile = value; }

    public String getProfileImageURL() { return profileImageURL; }
    public void setProfileImageURL(String value) { this.profileImageURL = value; }

    public String getProfileImageURLHTTPS() { return profileImageURLHTTPS; }
    public void setProfileImageURLHTTPS(String value) { this.profileImageURLHTTPS = value; }

    public String getProfileBannerURL() { return profileBannerURL; }
    public void setProfileBannerURL(String value) { this.profileBannerURL = value; }

    public String getProfileLinkColor() { return profileLinkColor; }
    public void setProfileLinkColor(String value) { this.profileLinkColor = value; }

    public String getProfileSidebarBorderColor() { return profileSidebarBorderColor; }
    public void setProfileSidebarBorderColor(String value) { this.profileSidebarBorderColor = value; }

    public String getProfileSidebarFillColor() { return profileSidebarFillColor; }
    public void setProfileSidebarFillColor(String value) { this.profileSidebarFillColor = value; }

    public String getProfileTextColor() { return profileTextColor; }
    public void setProfileTextColor(String value) { this.profileTextColor = value; }

    public Object getProfileUseBackgroundImage() { return profileUseBackgroundImage; }
    public void setProfileUseBackgroundImage(Object value) { this.profileUseBackgroundImage = value; }

    public Object getHasExtendedProfile() { return hasExtendedProfile; }
    public void setHasExtendedProfile(Object value) { this.hasExtendedProfile = value; }

    public boolean getDefaultProfile() { return defaultProfile; }
    public void setDefaultProfile(boolean value) { this.defaultProfile = value; }

    public boolean getDefaultProfileImage() { return defaultProfileImage; }
    public void setDefaultProfileImage(boolean value) { this.defaultProfileImage = value; }

    public Object getFollowing() { return following; }
    public void setFollowing(Object value) { this.following = value; }

    public Object getFollowRequestSent() { return followRequestSent; }
    public void setFollowRequestSent(Object value) { this.followRequestSent = value; }

    public Object getNotifications() { return notifications; }
    public void setNotifications(Object value) { this.notifications = value; }

    public String getTranslatorType() { return translatorType; }
    public void setTranslatorType(String value) { this.translatorType = value; }
}

// UserEntities.java

package io.quicktype;

import java.util.Map;

public class UserEntities {
    private Description url;
    private Description description;

    public Description getURL() { return url; }
    public void setURL(Description value) { this.url = value; }

    public Description getDescription() { return description; }
    public void setDescription(Description value) { this.description = value; }
}

// Description.java

package io.quicktype;

import java.util.Map;

public class Description {
    private URL[] urls;

    public URL[] getUrls() { return urls; }
    public void setUrls(URL[] value) { this.urls = value; }
}
